# Generated by Django 4.2.7 on 2023-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_delete_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
