# Generated by Django 4.2.7 on 2023-11-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_user_email_hash_user_encrypted_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encrypted_email',
        ),
    ]
