# Generated by Django 4.2.7 on 2023-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_user_encrypted_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iv',
            field=models.CharField(default='zero', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default='zero', max_length=40),
            preserve_default=False,
        ),
    ]
