# Generated by Django 4.2.7 on 2023-11-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_user_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
    ]
