# Generated by Django 4.2.7 on 2023-11-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_user_iv_remove_user_key_remove_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='24-06-1997', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='none@email.com', max_length=50),
        ),
    ]
